version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_chat
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local