version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_chat
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chat_go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chat

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_go
    ports:
      - '9999:9999'
    depends_on:
      - postgres
    networks:
      - chat


volumes:
  postgres-data:
    driver: local

networks:
  chat:
    driver: bridge